# coding: utf-8

"""
    Bungie.Net API

    These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.

    OpenAPI spec version: 2.0.0
    Contact: support@bungie.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.destiny_milestones_destiny_milestone_activity_phase import DestinyMilestonesDestinyMilestoneActivityPhase


class TestDestinyMilestonesDestinyMilestoneActivityPhase(unittest.TestCase):
    """ DestinyMilestonesDestinyMilestoneActivityPhase unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDestinyMilestonesDestinyMilestoneActivityPhase(self):
        """
        Test DestinyMilestonesDestinyMilestoneActivityPhase
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.destiny_milestones_destiny_milestone_activity_phase.DestinyMilestonesDestinyMilestoneActivityPhase()
        pass


if __name__ == '__main__':
    unittest.main()
