# coding: utf-8

"""
    Bungie.Net API

    These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.

    OpenAPI spec version: 2.0.0
    Contact: support@bungie.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class DestinyDefinitionsDestinyDamageTypeDefinition(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'transparent_icon_path': 'str',
        'show_icon': 'bool',
        'hash': 'int',
        'index': 'int',
        'redacted': 'bool'
    }

    attribute_map = {
        'transparent_icon_path': 'transparentIconPath',
        'show_icon': 'showIcon',
        'hash': 'hash',
        'index': 'index',
        'redacted': 'redacted'
    }

    def __init__(self, transparent_icon_path=None, show_icon=None, hash=None, index=None, redacted=None):
        """
        DestinyDefinitionsDestinyDamageTypeDefinition - a model defined in Swagger
        """

        self._transparent_icon_path = None
        self._show_icon = None
        self._hash = None
        self._index = None
        self._redacted = None
        self.discriminator = None

        if transparent_icon_path is not None:
          self.transparent_icon_path = transparent_icon_path
        if show_icon is not None:
          self.show_icon = show_icon
        if hash is not None:
          self.hash = hash
        if index is not None:
          self.index = index
        if redacted is not None:
          self.redacted = redacted

    @property
    def transparent_icon_path(self):
        """
        Gets the transparent_icon_path of this DestinyDefinitionsDestinyDamageTypeDefinition.
        A variant of the icon that is transparent and colorless.

        :return: The transparent_icon_path of this DestinyDefinitionsDestinyDamageTypeDefinition.
        :rtype: str
        """
        return self._transparent_icon_path

    @transparent_icon_path.setter
    def transparent_icon_path(self, transparent_icon_path):
        """
        Sets the transparent_icon_path of this DestinyDefinitionsDestinyDamageTypeDefinition.
        A variant of the icon that is transparent and colorless.

        :param transparent_icon_path: The transparent_icon_path of this DestinyDefinitionsDestinyDamageTypeDefinition.
        :type: str
        """

        self._transparent_icon_path = transparent_icon_path

    @property
    def show_icon(self):
        """
        Gets the show_icon of this DestinyDefinitionsDestinyDamageTypeDefinition.
        If TRUE, the game shows this damage type's icon.  Otherwise, it doesn't.  Whether you show it or not is up to you.

        :return: The show_icon of this DestinyDefinitionsDestinyDamageTypeDefinition.
        :rtype: bool
        """
        return self._show_icon

    @show_icon.setter
    def show_icon(self, show_icon):
        """
        Sets the show_icon of this DestinyDefinitionsDestinyDamageTypeDefinition.
        If TRUE, the game shows this damage type's icon.  Otherwise, it doesn't.  Whether you show it or not is up to you.

        :param show_icon: The show_icon of this DestinyDefinitionsDestinyDamageTypeDefinition.
        :type: bool
        """

        self._show_icon = show_icon

    @property
    def hash(self):
        """
        Gets the hash of this DestinyDefinitionsDestinyDamageTypeDefinition.
        The unique identifier for this entity.  Guaranteed to be unique for the type of entity, but not globally.  When entities refer to each other in Destiny content, it is this hash that they are referring to.

        :return: The hash of this DestinyDefinitionsDestinyDamageTypeDefinition.
        :rtype: int
        """
        return self._hash

    @hash.setter
    def hash(self, hash):
        """
        Sets the hash of this DestinyDefinitionsDestinyDamageTypeDefinition.
        The unique identifier for this entity.  Guaranteed to be unique for the type of entity, but not globally.  When entities refer to each other in Destiny content, it is this hash that they are referring to.

        :param hash: The hash of this DestinyDefinitionsDestinyDamageTypeDefinition.
        :type: int
        """

        self._hash = hash

    @property
    def index(self):
        """
        Gets the index of this DestinyDefinitionsDestinyDamageTypeDefinition.
        The index of the entity as it was found in the investment tables.

        :return: The index of this DestinyDefinitionsDestinyDamageTypeDefinition.
        :rtype: int
        """
        return self._index

    @index.setter
    def index(self, index):
        """
        Sets the index of this DestinyDefinitionsDestinyDamageTypeDefinition.
        The index of the entity as it was found in the investment tables.

        :param index: The index of this DestinyDefinitionsDestinyDamageTypeDefinition.
        :type: int
        """

        self._index = index

    @property
    def redacted(self):
        """
        Gets the redacted of this DestinyDefinitionsDestinyDamageTypeDefinition.
        If this is true, then there is an entity with this identifier/type combination, but BNet isnot yet allowed to show it.  Sorry!

        :return: The redacted of this DestinyDefinitionsDestinyDamageTypeDefinition.
        :rtype: bool
        """
        return self._redacted

    @redacted.setter
    def redacted(self, redacted):
        """
        Sets the redacted of this DestinyDefinitionsDestinyDamageTypeDefinition.
        If this is true, then there is an entity with this identifier/type combination, but BNet isnot yet allowed to show it.  Sorry!

        :param redacted: The redacted of this DestinyDefinitionsDestinyDamageTypeDefinition.
        :type: bool
        """

        self._redacted = redacted

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, DestinyDefinitionsDestinyDamageTypeDefinition):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
