# coding: utf-8

"""
    Bungie.Net API

    These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.

    OpenAPI spec version: 2.0.0
    Contact: support@bungie.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class DestinyEntitiesItemsDestinyItemRenderComponent(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'use_custom_dyes': 'bool',
        'art_regions': 'dict(str, int)'
    }

    attribute_map = {
        'use_custom_dyes': 'useCustomDyes',
        'art_regions': 'artRegions'
    }

    def __init__(self, use_custom_dyes=None, art_regions=None):
        """
        DestinyEntitiesItemsDestinyItemRenderComponent - a model defined in Swagger
        """

        self._use_custom_dyes = None
        self._art_regions = None
        self.discriminator = None

        if use_custom_dyes is not None:
          self.use_custom_dyes = use_custom_dyes
        if art_regions is not None:
          self.art_regions = art_regions

    @property
    def use_custom_dyes(self):
        """
        Gets the use_custom_dyes of this DestinyEntitiesItemsDestinyItemRenderComponent.
        If you should use custom dyes on this item, it will be indicated here.

        :return: The use_custom_dyes of this DestinyEntitiesItemsDestinyItemRenderComponent.
        :rtype: bool
        """
        return self._use_custom_dyes

    @use_custom_dyes.setter
    def use_custom_dyes(self, use_custom_dyes):
        """
        Sets the use_custom_dyes of this DestinyEntitiesItemsDestinyItemRenderComponent.
        If you should use custom dyes on this item, it will be indicated here.

        :param use_custom_dyes: The use_custom_dyes of this DestinyEntitiesItemsDestinyItemRenderComponent.
        :type: bool
        """

        self._use_custom_dyes = use_custom_dyes

    @property
    def art_regions(self):
        """
        Gets the art_regions of this DestinyEntitiesItemsDestinyItemRenderComponent.
        A dictionary for rendering gear components, with:  key = Art Arrangement Region Index  value = The chosen Arrangement Index for the Region, based on the value of a stat on the item used for making the choice.

        :return: The art_regions of this DestinyEntitiesItemsDestinyItemRenderComponent.
        :rtype: dict(str, int)
        """
        return self._art_regions

    @art_regions.setter
    def art_regions(self, art_regions):
        """
        Sets the art_regions of this DestinyEntitiesItemsDestinyItemRenderComponent.
        A dictionary for rendering gear components, with:  key = Art Arrangement Region Index  value = The chosen Arrangement Index for the Region, based on the value of a stat on the item used for making the choice.

        :param art_regions: The art_regions of this DestinyEntitiesItemsDestinyItemRenderComponent.
        :type: dict(str, int)
        """

        self._art_regions = art_regions

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, DestinyEntitiesItemsDestinyItemRenderComponent):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
