# coding: utf-8

"""
    Bungie.Net API

    These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.

    OpenAPI spec version: 2.0.0
    Contact: support@bungie.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class DestinyDefinitionsDestinyItemInvestmentStatDefinition(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'stat_type_hash': 'int',
        'value': 'int'
    }

    attribute_map = {
        'stat_type_hash': 'statTypeHash',
        'value': 'value'
    }

    def __init__(self, stat_type_hash=None, value=None):
        """
        DestinyDefinitionsDestinyItemInvestmentStatDefinition - a model defined in Swagger
        """

        self._stat_type_hash = None
        self._value = None
        self.discriminator = None

        if stat_type_hash is not None:
          self.stat_type_hash = stat_type_hash
        if value is not None:
          self.value = value

    @property
    def stat_type_hash(self):
        """
        Gets the stat_type_hash of this DestinyDefinitionsDestinyItemInvestmentStatDefinition.
        The hash identifier for the DestinyStatDefinition defining this stat.

        :return: The stat_type_hash of this DestinyDefinitionsDestinyItemInvestmentStatDefinition.
        :rtype: int
        """
        return self._stat_type_hash

    @stat_type_hash.setter
    def stat_type_hash(self, stat_type_hash):
        """
        Sets the stat_type_hash of this DestinyDefinitionsDestinyItemInvestmentStatDefinition.
        The hash identifier for the DestinyStatDefinition defining this stat.

        :param stat_type_hash: The stat_type_hash of this DestinyDefinitionsDestinyItemInvestmentStatDefinition.
        :type: int
        """

        self._stat_type_hash = stat_type_hash

    @property
    def value(self):
        """
        Gets the value of this DestinyDefinitionsDestinyItemInvestmentStatDefinition.
        The raw \"Investment\" value for the stat, before transformations are performedto turn this raw stat into stats that are displayed in the game UI.

        :return: The value of this DestinyDefinitionsDestinyItemInvestmentStatDefinition.
        :rtype: int
        """
        return self._value

    @value.setter
    def value(self, value):
        """
        Sets the value of this DestinyDefinitionsDestinyItemInvestmentStatDefinition.
        The raw \"Investment\" value for the stat, before transformations are performedto turn this raw stat into stats that are displayed in the game UI.

        :param value: The value of this DestinyDefinitionsDestinyItemInvestmentStatDefinition.
        :type: int
        """

        self._value = value

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, DestinyDefinitionsDestinyItemInvestmentStatDefinition):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
