# coding: utf-8

"""
    Bungie.Net API

    These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.

    OpenAPI spec version: 2.0.0
    Contact: support@bungie.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class DestinyDefinitionsItemsDestinyItemTierTypeInfusionBlock(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'base_quality_transfer_ratio': 'float',
        'minimum_quality_increment': 'int'
    }

    attribute_map = {
        'base_quality_transfer_ratio': 'baseQualityTransferRatio',
        'minimum_quality_increment': 'minimumQualityIncrement'
    }

    def __init__(self, base_quality_transfer_ratio=None, minimum_quality_increment=None):
        """
        DestinyDefinitionsItemsDestinyItemTierTypeInfusionBlock - a model defined in Swagger
        """

        self._base_quality_transfer_ratio = None
        self._minimum_quality_increment = None
        self.discriminator = None

        if base_quality_transfer_ratio is not None:
          self.base_quality_transfer_ratio = base_quality_transfer_ratio
        if minimum_quality_increment is not None:
          self.minimum_quality_increment = minimum_quality_increment

    @property
    def base_quality_transfer_ratio(self):
        """
        Gets the base_quality_transfer_ratio of this DestinyDefinitionsItemsDestinyItemTierTypeInfusionBlock.
        The default portion of quality that will transfer from the infuser to the infusee item.(InfuserQuality - InfuseeQuality) * baseQualityTransferRatio = base quality transferred.

        :return: The base_quality_transfer_ratio of this DestinyDefinitionsItemsDestinyItemTierTypeInfusionBlock.
        :rtype: float
        """
        return self._base_quality_transfer_ratio

    @base_quality_transfer_ratio.setter
    def base_quality_transfer_ratio(self, base_quality_transfer_ratio):
        """
        Sets the base_quality_transfer_ratio of this DestinyDefinitionsItemsDestinyItemTierTypeInfusionBlock.
        The default portion of quality that will transfer from the infuser to the infusee item.(InfuserQuality - InfuseeQuality) * baseQualityTransferRatio = base quality transferred.

        :param base_quality_transfer_ratio: The base_quality_transfer_ratio of this DestinyDefinitionsItemsDestinyItemTierTypeInfusionBlock.
        :type: float
        """

        self._base_quality_transfer_ratio = base_quality_transfer_ratio

    @property
    def minimum_quality_increment(self):
        """
        Gets the minimum_quality_increment of this DestinyDefinitionsItemsDestinyItemTierTypeInfusionBlock.
        As long as InfuserQuality > InfuseeQuality, the amount of quality bestowed is guaranteedto be at least this value, even if the transferRatio would dictate that it should be less.The total amount of quality that ends up in the Infusee cannot exceed the Infuser's quality however(for instance, if you infuse a 300 item with a 301 item and the minimum quality incrementis 10, the infused item will not end up with 310 quality)

        :return: The minimum_quality_increment of this DestinyDefinitionsItemsDestinyItemTierTypeInfusionBlock.
        :rtype: int
        """
        return self._minimum_quality_increment

    @minimum_quality_increment.setter
    def minimum_quality_increment(self, minimum_quality_increment):
        """
        Sets the minimum_quality_increment of this DestinyDefinitionsItemsDestinyItemTierTypeInfusionBlock.
        As long as InfuserQuality > InfuseeQuality, the amount of quality bestowed is guaranteedto be at least this value, even if the transferRatio would dictate that it should be less.The total amount of quality that ends up in the Infusee cannot exceed the Infuser's quality however(for instance, if you infuse a 300 item with a 301 item and the minimum quality incrementis 10, the infused item will not end up with 310 quality)

        :param minimum_quality_increment: The minimum_quality_increment of this DestinyDefinitionsItemsDestinyItemTierTypeInfusionBlock.
        :type: int
        """

        self._minimum_quality_increment = minimum_quality_increment

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, DestinyDefinitionsItemsDestinyItemTierTypeInfusionBlock):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
