# coding: utf-8

"""
    Bungie.Net API

    These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.

    OpenAPI spec version: 2.0.0
    Contact: support@bungie.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class DestinyDefinitionsMilestonesDestinyMilestoneQuestRewardItem(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'vendor_hash': 'int',
        'vendor_item_index': 'int',
        'item_hash': 'int',
        'item_instance_id': 'int',
        'quantity': 'int'
    }

    attribute_map = {
        'vendor_hash': 'vendorHash',
        'vendor_item_index': 'vendorItemIndex',
        'item_hash': 'itemHash',
        'item_instance_id': 'itemInstanceId',
        'quantity': 'quantity'
    }

    def __init__(self, vendor_hash=None, vendor_item_index=None, item_hash=None, item_instance_id=None, quantity=None):
        """
        DestinyDefinitionsMilestonesDestinyMilestoneQuestRewardItem - a model defined in Swagger
        """

        self._vendor_hash = None
        self._vendor_item_index = None
        self._item_hash = None
        self._item_instance_id = None
        self._quantity = None
        self.discriminator = None

        if vendor_hash is not None:
          self.vendor_hash = vendor_hash
        if vendor_item_index is not None:
          self.vendor_item_index = vendor_item_index
        if item_hash is not None:
          self.item_hash = item_hash
        if item_instance_id is not None:
          self.item_instance_id = item_instance_id
        if quantity is not None:
          self.quantity = quantity

    @property
    def vendor_hash(self):
        """
        Gets the vendor_hash of this DestinyDefinitionsMilestonesDestinyMilestoneQuestRewardItem.
        The quest reward item *may* be associated with a vendor.  If so,this is that vendor.  Use this hash to look up the DestinyVendorDefinition.

        :return: The vendor_hash of this DestinyDefinitionsMilestonesDestinyMilestoneQuestRewardItem.
        :rtype: int
        """
        return self._vendor_hash

    @vendor_hash.setter
    def vendor_hash(self, vendor_hash):
        """
        Sets the vendor_hash of this DestinyDefinitionsMilestonesDestinyMilestoneQuestRewardItem.
        The quest reward item *may* be associated with a vendor.  If so,this is that vendor.  Use this hash to look up the DestinyVendorDefinition.

        :param vendor_hash: The vendor_hash of this DestinyDefinitionsMilestonesDestinyMilestoneQuestRewardItem.
        :type: int
        """

        self._vendor_hash = vendor_hash

    @property
    def vendor_item_index(self):
        """
        Gets the vendor_item_index of this DestinyDefinitionsMilestonesDestinyMilestoneQuestRewardItem.
        The quest reward item *may* be associated with a vendor.  If so,this is the index of the item being sold, which we can use at runtimeto find instanced item information for the reward item.

        :return: The vendor_item_index of this DestinyDefinitionsMilestonesDestinyMilestoneQuestRewardItem.
        :rtype: int
        """
        return self._vendor_item_index

    @vendor_item_index.setter
    def vendor_item_index(self, vendor_item_index):
        """
        Sets the vendor_item_index of this DestinyDefinitionsMilestonesDestinyMilestoneQuestRewardItem.
        The quest reward item *may* be associated with a vendor.  If so,this is the index of the item being sold, which we can use at runtimeto find instanced item information for the reward item.

        :param vendor_item_index: The vendor_item_index of this DestinyDefinitionsMilestonesDestinyMilestoneQuestRewardItem.
        :type: int
        """

        self._vendor_item_index = vendor_item_index

    @property
    def item_hash(self):
        """
        Gets the item_hash of this DestinyDefinitionsMilestonesDestinyMilestoneQuestRewardItem.
        The hash identifier for the item in question.  Use it to look up the item's DestinyInventoryItemDefinition.

        :return: The item_hash of this DestinyDefinitionsMilestonesDestinyMilestoneQuestRewardItem.
        :rtype: int
        """
        return self._item_hash

    @item_hash.setter
    def item_hash(self, item_hash):
        """
        Sets the item_hash of this DestinyDefinitionsMilestonesDestinyMilestoneQuestRewardItem.
        The hash identifier for the item in question.  Use it to look up the item's DestinyInventoryItemDefinition.

        :param item_hash: The item_hash of this DestinyDefinitionsMilestonesDestinyMilestoneQuestRewardItem.
        :type: int
        """

        self._item_hash = item_hash

    @property
    def item_instance_id(self):
        """
        Gets the item_instance_id of this DestinyDefinitionsMilestonesDestinyMilestoneQuestRewardItem.
        If this quantity is referring to a specific instance of an item, this will have the item's instance ID.Normally, this will be null.

        :return: The item_instance_id of this DestinyDefinitionsMilestonesDestinyMilestoneQuestRewardItem.
        :rtype: int
        """
        return self._item_instance_id

    @item_instance_id.setter
    def item_instance_id(self, item_instance_id):
        """
        Sets the item_instance_id of this DestinyDefinitionsMilestonesDestinyMilestoneQuestRewardItem.
        If this quantity is referring to a specific instance of an item, this will have the item's instance ID.Normally, this will be null.

        :param item_instance_id: The item_instance_id of this DestinyDefinitionsMilestonesDestinyMilestoneQuestRewardItem.
        :type: int
        """

        self._item_instance_id = item_instance_id

    @property
    def quantity(self):
        """
        Gets the quantity of this DestinyDefinitionsMilestonesDestinyMilestoneQuestRewardItem.
        The amount of the item needed/available depending on the context of where DestinyItemQuantity is being used.

        :return: The quantity of this DestinyDefinitionsMilestonesDestinyMilestoneQuestRewardItem.
        :rtype: int
        """
        return self._quantity

    @quantity.setter
    def quantity(self, quantity):
        """
        Sets the quantity of this DestinyDefinitionsMilestonesDestinyMilestoneQuestRewardItem.
        The amount of the item needed/available depending on the context of where DestinyItemQuantity is being used.

        :param quantity: The quantity of this DestinyDefinitionsMilestonesDestinyMilestoneQuestRewardItem.
        :type: int
        """

        self._quantity = quantity

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, DestinyDefinitionsMilestonesDestinyMilestoneQuestRewardItem):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
