# coding: utf-8

"""
    Bungie.Net API

    These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.

    OpenAPI spec version: 2.0.0
    Contact: support@bungie.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class TagsModelsContractsTagResponse(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'tag_text': 'str',
        'ignore_status': 'ComponentsschemasIgnoresIgnoreResponse'
    }

    attribute_map = {
        'tag_text': 'tagText',
        'ignore_status': 'ignoreStatus'
    }

    def __init__(self, tag_text=None, ignore_status=None):
        """
        TagsModelsContractsTagResponse - a model defined in Swagger
        """

        self._tag_text = None
        self._ignore_status = None
        self.discriminator = None

        if tag_text is not None:
          self.tag_text = tag_text
        if ignore_status is not None:
          self.ignore_status = ignore_status

    @property
    def tag_text(self):
        """
        Gets the tag_text of this TagsModelsContractsTagResponse.

        :return: The tag_text of this TagsModelsContractsTagResponse.
        :rtype: str
        """
        return self._tag_text

    @tag_text.setter
    def tag_text(self, tag_text):
        """
        Sets the tag_text of this TagsModelsContractsTagResponse.

        :param tag_text: The tag_text of this TagsModelsContractsTagResponse.
        :type: str
        """

        self._tag_text = tag_text

    @property
    def ignore_status(self):
        """
        Gets the ignore_status of this TagsModelsContractsTagResponse.

        :return: The ignore_status of this TagsModelsContractsTagResponse.
        :rtype: ComponentsschemasIgnoresIgnoreResponse
        """
        return self._ignore_status

    @ignore_status.setter
    def ignore_status(self, ignore_status):
        """
        Sets the ignore_status of this TagsModelsContractsTagResponse.

        :param ignore_status: The ignore_status of this TagsModelsContractsTagResponse.
        :type: ComponentsschemasIgnoresIgnoreResponse
        """

        self._ignore_status = ignore_status

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, TagsModelsContractsTagResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
