# coding: utf-8

"""
    Bungie.Net API

    These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.

    OpenAPI spec version: 2.0.0
    Contact: support@bungie.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class TrendingTrendingDetail(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'identifier': 'str',
        'entity_type': 'ComponentsschemasTrendingTrendingEntryType',
        'news': 'ComponentsschemasTrendingTrendingEntryNews',
        'support': 'ComponentsschemasTrendingTrendingEntrySupportArticle',
        'destiny_item': 'ComponentsschemasTrendingTrendingEntryDestinyItem',
        'destiny_activity': 'ComponentsschemasTrendingTrendingEntryDestinyActivity',
        'destiny_ritual': 'ComponentsschemasTrendingTrendingEntryDestinyRitual',
        'creation': 'ComponentsschemasTrendingTrendingEntryCommunityCreation',
        'stream': 'ComponentsschemasTrendingTrendingEntryCommunityStream'
    }

    attribute_map = {
        'identifier': 'identifier',
        'entity_type': 'entityType',
        'news': 'news',
        'support': 'support',
        'destiny_item': 'destinyItem',
        'destiny_activity': 'destinyActivity',
        'destiny_ritual': 'destinyRitual',
        'creation': 'creation',
        'stream': 'stream'
    }

    def __init__(self, identifier=None, entity_type=None, news=None, support=None, destiny_item=None, destiny_activity=None, destiny_ritual=None, creation=None, stream=None):
        """
        TrendingTrendingDetail - a model defined in Swagger
        """

        self._identifier = None
        self._entity_type = None
        self._news = None
        self._support = None
        self._destiny_item = None
        self._destiny_activity = None
        self._destiny_ritual = None
        self._creation = None
        self._stream = None
        self.discriminator = None

        if identifier is not None:
          self.identifier = identifier
        if entity_type is not None:
          self.entity_type = entity_type
        if news is not None:
          self.news = news
        if support is not None:
          self.support = support
        if destiny_item is not None:
          self.destiny_item = destiny_item
        if destiny_activity is not None:
          self.destiny_activity = destiny_activity
        if destiny_ritual is not None:
          self.destiny_ritual = destiny_ritual
        if creation is not None:
          self.creation = creation
        if stream is not None:
          self.stream = stream

    @property
    def identifier(self):
        """
        Gets the identifier of this TrendingTrendingDetail.

        :return: The identifier of this TrendingTrendingDetail.
        :rtype: str
        """
        return self._identifier

    @identifier.setter
    def identifier(self, identifier):
        """
        Sets the identifier of this TrendingTrendingDetail.

        :param identifier: The identifier of this TrendingTrendingDetail.
        :type: str
        """

        self._identifier = identifier

    @property
    def entity_type(self):
        """
        Gets the entity_type of this TrendingTrendingDetail.

        :return: The entity_type of this TrendingTrendingDetail.
        :rtype: ComponentsschemasTrendingTrendingEntryType
        """
        return self._entity_type

    @entity_type.setter
    def entity_type(self, entity_type):
        """
        Sets the entity_type of this TrendingTrendingDetail.

        :param entity_type: The entity_type of this TrendingTrendingDetail.
        :type: ComponentsschemasTrendingTrendingEntryType
        """

        self._entity_type = entity_type

    @property
    def news(self):
        """
        Gets the news of this TrendingTrendingDetail.

        :return: The news of this TrendingTrendingDetail.
        :rtype: ComponentsschemasTrendingTrendingEntryNews
        """
        return self._news

    @news.setter
    def news(self, news):
        """
        Sets the news of this TrendingTrendingDetail.

        :param news: The news of this TrendingTrendingDetail.
        :type: ComponentsschemasTrendingTrendingEntryNews
        """

        self._news = news

    @property
    def support(self):
        """
        Gets the support of this TrendingTrendingDetail.

        :return: The support of this TrendingTrendingDetail.
        :rtype: ComponentsschemasTrendingTrendingEntrySupportArticle
        """
        return self._support

    @support.setter
    def support(self, support):
        """
        Sets the support of this TrendingTrendingDetail.

        :param support: The support of this TrendingTrendingDetail.
        :type: ComponentsschemasTrendingTrendingEntrySupportArticle
        """

        self._support = support

    @property
    def destiny_item(self):
        """
        Gets the destiny_item of this TrendingTrendingDetail.

        :return: The destiny_item of this TrendingTrendingDetail.
        :rtype: ComponentsschemasTrendingTrendingEntryDestinyItem
        """
        return self._destiny_item

    @destiny_item.setter
    def destiny_item(self, destiny_item):
        """
        Sets the destiny_item of this TrendingTrendingDetail.

        :param destiny_item: The destiny_item of this TrendingTrendingDetail.
        :type: ComponentsschemasTrendingTrendingEntryDestinyItem
        """

        self._destiny_item = destiny_item

    @property
    def destiny_activity(self):
        """
        Gets the destiny_activity of this TrendingTrendingDetail.

        :return: The destiny_activity of this TrendingTrendingDetail.
        :rtype: ComponentsschemasTrendingTrendingEntryDestinyActivity
        """
        return self._destiny_activity

    @destiny_activity.setter
    def destiny_activity(self, destiny_activity):
        """
        Sets the destiny_activity of this TrendingTrendingDetail.

        :param destiny_activity: The destiny_activity of this TrendingTrendingDetail.
        :type: ComponentsschemasTrendingTrendingEntryDestinyActivity
        """

        self._destiny_activity = destiny_activity

    @property
    def destiny_ritual(self):
        """
        Gets the destiny_ritual of this TrendingTrendingDetail.

        :return: The destiny_ritual of this TrendingTrendingDetail.
        :rtype: ComponentsschemasTrendingTrendingEntryDestinyRitual
        """
        return self._destiny_ritual

    @destiny_ritual.setter
    def destiny_ritual(self, destiny_ritual):
        """
        Sets the destiny_ritual of this TrendingTrendingDetail.

        :param destiny_ritual: The destiny_ritual of this TrendingTrendingDetail.
        :type: ComponentsschemasTrendingTrendingEntryDestinyRitual
        """

        self._destiny_ritual = destiny_ritual

    @property
    def creation(self):
        """
        Gets the creation of this TrendingTrendingDetail.

        :return: The creation of this TrendingTrendingDetail.
        :rtype: ComponentsschemasTrendingTrendingEntryCommunityCreation
        """
        return self._creation

    @creation.setter
    def creation(self, creation):
        """
        Sets the creation of this TrendingTrendingDetail.

        :param creation: The creation of this TrendingTrendingDetail.
        :type: ComponentsschemasTrendingTrendingEntryCommunityCreation
        """

        self._creation = creation

    @property
    def stream(self):
        """
        Gets the stream of this TrendingTrendingDetail.

        :return: The stream of this TrendingTrendingDetail.
        :rtype: ComponentsschemasTrendingTrendingEntryCommunityStream
        """
        return self._stream

    @stream.setter
    def stream(self, stream):
        """
        Sets the stream of this TrendingTrendingDetail.

        :param stream: The stream of this TrendingTrendingDetail.
        :type: ComponentsschemasTrendingTrendingEntryCommunityStream
        """

        self._stream = stream

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, TrendingTrendingDetail):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
